name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]


concurrency:
  group: ${{ github.ref }}

jobs:
  lint:
    name: ktlint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/workflows/gradle-caches
        with:
          key-prefix: gradle-lint
      - name: Spotless
        run: ./gradlew :meteor:core:spotlessCheck --scan :meteor:viewmodel:spotlessCheck --scan
      - name: Ktlint
        run: ./gradlew :meteor:core:ktlintCheck --scan :meteor:viewmodel:ktlintCheck --scan
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/workflows/gradle-caches
        with:
          key-prefix: gradle-build
      - name: Build
        run: ../gradlew :meteor:core:build :meteor:viewmodel:build
  test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/workflows/gradle-caches
        with:
          key-prefix: gradle-test
      - name: Unit tests
        run: ./gradlew :meteor-core:test :meteor-test:test :meteor-viewmodel:test
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest
