name: Publish Snapshot builds

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Snapshot build and publish
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - name: Release build
        run: ./gradlew :meteor-viewmodel:assemble :meteor-core:assemble
      - name: Source jar
        run: ./gradlew androidSourcesJar
      - name: Publish release
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          SNAPSHOT: true
